### ISSUE TITLE
Unexpected behaviour in pandas dataframe .loc[]

### ISSUE THREAD

**Issue by njiles** [asottile/add-trailing-comma#159]
Hi, thanks for the great tool!

I recently came across some behaviour that surprised me - I'm not sure if it's a bug or a misunderstanding on my part.

Where `df` is a pandas DataFrame and `s` is a pandas Series, the following snippet
```python
df.loc[s, ]
```
gets converted to
```python
df.loc[s,]
```
(note that the whitespace between the comma and the `]` has been removed). Per https://github.com/asottile/add-trailing-comma#remove-unnecessary-commas, I expected the result to be
```python
df.loc[s]
```

If you can clear up my confusion I would appreciate it, thank you.

(Aside: the current result causes flake8 to raise [E231](https://www.flake8rules.com/rules/E231.html) `Missing whitespace after ',', ';', or ':'`.)

Pre-commit config:
```yaml
  - repo: https://github.com/asottile/add-trailing-comma
    rev: v2.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]
```
